modules:
 - char:
     - templates:
         - Makefile.template
         - lkm.template
         - test.template
 - block:
     - templates:
         - Makefile.template
         - lkm.template
         - test.template
 - net:
     - templates:
         - Makefile.template
         - lkm.template
         - test.template
 - vma:
     - templates:
         - Makefile.template
         - lkm.template
         - test.template
