lkm_charachter_device:
    lkm_charachter_device/Makefile.template
    lkm_charachter_device/lkm.template
    lkm_charachter_device/test.template

lkm_block_device:
    lkm_block_device/Makefile.template
    lkm_block_device/lkm.template
    lkm_block_device/test.template

lkm_network_interfaces:
    lkm_network_interfaces/Makefile.template
    lkm_network_interfaces/lkm.template
    lkm_network_interfaces/test.template

lkm_vma:
    lkm_vma/Makefile.template
    lkm_vma/lkm.template
    lkm_vma/test.template

